"""add _city col in profile

Revision ID: 0c73e2832547
Revises: 0e7e9264a87c
Create Date: 2025-07-15 05:30:23.983987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c73e2832547'
down_revision: Union[str, None] = '0e7e9264a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('_city', sa.String(), nullable=True))
    op.drop_constraint('profiles_city_full_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'cities', ['_city'], ['full_name'])
    op.drop_column('profiles', 'city_full')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city_full', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_city_full_fkey', 'profiles', 'cities', ['city_full'], ['full_name'])
    op.drop_column('profiles', '_city')
    # ### end Alembic commands ###
