"""add city_full col in profile

Revision ID: 0e7e9264a87c
Revises: 4f541b35ce0b
Create Date: 2025-07-15 05:08:55.389483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7e9264a87c'
down_revision: Union[str, None] = '4f541b35ce0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city_full', sa.String(), nullable=True))
    op.drop_constraint('profiles_city_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'cities', ['city_full'], ['full_name'])
    op.drop_column('profiles', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_city_fkey', 'profiles', 'cities', ['city'], ['full_name'])
    op.drop_column('profiles', 'city_full')
    # ### end Alembic commands ###
