"""add crop_image_url field for ProfileImage

Revision ID: 18a1b806dc65
Revises: 01609a6646ad
Create Date: 2025-08-04 01:48:40.425743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = '18a1b806dc65'
down_revision: Union[str, None] = '01609a6646ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'profile_images',
        sa.Column('crop_photo_url', sa.String(), nullable=True)
    )

    # Заполни значение для существующих строк (если нужно)
    op.execute(
        "UPDATE profile_images SET crop_photo_url = 'https://example.com/default.jpg'"
    )

    # Сделай поле обязательным
    op.alter_column('profile_images', 'crop_photo_url', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_images', 'crop_photo_url')
    # ### end Alembic commands ###
