"""empty message

Revision ID: 1ab8e7260969
Revises: 38bb95968d6d
Create Date: 2025-07-14 02:33:23.833748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab8e7260969'
down_revision: Union[str, None] = '38bb95968d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_responses', sa.Column('video_intro', sa.String(), nullable=True))
    op.drop_column('profile_responses', 'self_test_url')
    op.add_column('profiles', sa.Column('clothing_size', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('profiles', sa.Column('shoe_size', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('profiles', sa.Column('bust_volume', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('profiles', sa.Column('waist_volume', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('profiles', sa.Column('hip_volume', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_index('ix_profiles_foot_size', table_name='profiles')
    op.drop_index('ix_profiles_hip_width', table_name='profiles')
    op.drop_index('ix_profiles_shoulder_width', table_name='profiles')
    op.create_index(op.f('ix_profiles_bust_volume'), 'profiles', ['bust_volume'], unique=False)
    op.create_index(op.f('ix_profiles_clothing_size'), 'profiles', ['clothing_size'], unique=False)
    op.create_index(op.f('ix_profiles_hip_volume'), 'profiles', ['hip_volume'], unique=False)
    op.create_index(op.f('ix_profiles_shoe_size'), 'profiles', ['shoe_size'], unique=False)
    op.create_index(op.f('ix_profiles_waist_volume'), 'profiles', ['waist_volume'], unique=False)
    op.drop_column('profiles', 'hip_width')
    op.drop_column('profiles', 'shoulder_width')
    op.drop_column('profiles', 'foot_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('foot_size', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('shoulder_width', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('hip_width', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiles_waist_volume'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_shoe_size'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_hip_volume'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_clothing_size'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_bust_volume'), table_name='profiles')
    op.create_index('ix_profiles_shoulder_width', 'profiles', ['shoulder_width'], unique=False)
    op.create_index('ix_profiles_hip_width', 'profiles', ['hip_width'], unique=False)
    op.create_index('ix_profiles_foot_size', 'profiles', ['foot_size'], unique=False)
    op.drop_column('profiles', 'hip_volume')
    op.drop_column('profiles', 'waist_volume')
    op.drop_column('profiles', 'bust_volume')
    op.drop_column('profiles', 'shoe_size')
    op.drop_column('profiles', 'clothing_size')
    op.add_column('profile_responses', sa.Column('self_test_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile_responses', 'video_intro')
    # ### end Alembic commands ###
