"""reports tables init

Revision ID: 418e19353790
Revises: 1a635e9e73d3
Create Date: 2025-06-11 20:30:58.869500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418e19353790'
down_revision: Union[str, None] = '1a635e9e73d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_predicates', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_predicates', type_='unique')
    # ### end Alembic commands ###
