"""add _city col in profile

Revision ID: 4f12d2e22838
Revises: 0c73e2832547
Create Date: 2025-07-15 05:33:55.686213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f12d2e22838'
down_revision: Union[str, None] = '0c73e2832547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    op.drop_constraint('profiles__city_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'cities', ['city'], ['full_name'])
    op.drop_column('profiles', '_city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles__city_fkey', 'profiles', 'cities', ['_city'], ['full_name'])
    op.drop_column('profiles', 'city')
    # ### end Alembic commands ###
