"""add city col in profile

Revision ID: 4f541b35ce0b
Revises: 29fa918a30c4
Create Date: 2025-07-15 04:56:58.734396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f541b35ce0b'
down_revision: Union[str, None] = '29fa918a30c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'cities', ['city'], ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'city')
    # ### end Alembic commands ###
