"""empty message

Revision ID: 5fae61d6a534
Revises: 8e9239a17b74
Create Date: 2025-08-21 21:25:36.327010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fae61d6a534'
down_revision: Union[str, None] = '8e9239a17b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_responses', sa.Column('self_test_url', sa.String(), nullable=True))
    op.drop_column('profile_responses', 'video_intro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_responses', sa.Column('video_intro', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile_responses', 'self_test_url')
    # ### end Alembic commands ###
