"""reports tables init

Revision ID: 8fffa2d021e6
Revises: cb00c3937966
Create Date: 2025-06-11 20:51:44.423942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fffa2d021e6'
down_revision: Union[str, None] = 'cb00c3937966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles_reports', ['id'])
    op.create_unique_constraint(None, 'reports', ['id'])
    # op.create_foreign_key(None, 'reports', 'castings', ['title'], ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_constraint(None, 'profiles_reports', type_='unique')
    # ### end Alembic commands ###
