"""add self_test_url coll in Responses

Revision ID: 909afbc2d5b9
Revises: f97bfa02af3d
Create Date: 2025-05-25 20:14:01.667392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909afbc2d5b9'
down_revision: Union[str, None] = 'f97bfa02af3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'casting_images', ['id'])
    op.create_unique_constraint(None, 'casting_posts', ['id'])
    op.create_unique_constraint(None, 'castings', ['id'])
    op.create_unique_constraint(None, 'profile_images', ['id'])
    op.add_column('profile_responses', sa.Column('self_test_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profile_responses', ['id'])
    op.create_unique_constraint(None, 'profiles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profile_responses', type_='unique')
    op.drop_column('profile_responses', 'self_test_url')
    op.drop_constraint(None, 'profile_images', type_='unique')
    op.drop_constraint(None, 'castings', type_='unique')
    op.drop_constraint(None, 'casting_posts', type_='unique')
    op.drop_constraint(None, 'casting_images', type_='unique')
    # ### end Alembic commands ###
