"""empty message

Revision ID: 9eed45e35614
Revises: 746bd0220452
Create Date: 2025-07-14 05:27:59.164211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eed45e35614'
down_revision: Union[str, None] = '746bd0220452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_predicates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_predicates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('auth_predicate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('administrator', 'user', name='modelroles'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_predicates_pkey'),
    sa.UniqueConstraint('id', name='auth_predicates_id_key')
    )
    # ### end Alembic commands ###
