"""empty message

Revision ID: a08ff9544e3f
Revises: 5fae61d6a534
Create Date: 2025-08-29 10:55:43.532462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08ff9544e3f'
down_revision: Union[str, None] = '5fae61d6a534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'profiles_reports',
        sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'profiles_reports',
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now())
    )

    op.add_column(
        'reports',
        sa.Column('public_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_reports_public_id'), 'reports', ['public_id'], unique=True)

    op.drop_column('reports', 'link')

    # убираем дефолты после того как данные заполнены
    op.alter_column('profiles_reports', 'favorite', server_default=None)
    op.alter_column('profiles_reports', 'updated_at', server_default=None)
    op.alter_column('reports', 'public_id', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reports_public_id'), table_name='reports')
    op.drop_column('reports', 'public_id')
    op.drop_column('profiles_reports', 'updated_at')
    op.drop_column('profiles_reports', 'favorite')
    # ### end Alembic commands ###
