"""fix image type

Revision ID: ad797b7f6ba8
Revises: d2148964e776
Create Date: 2025-07-14 23:05:43.600581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad797b7f6ba8'
down_revision: Union[str, None] = 'd2148964e776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_images', 'image_type',
               existing_type=postgresql.ENUM('portrait', 'side_profile', 'full_body', 'other', name='image_type'),
               type_=sa.Enum('portrait', 'side_profile', 'full_body', 'other', name='image_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'other'::image_type"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_images', 'image_type',
               existing_type=sa.Enum('portrait', 'side_profile', 'full_body', 'other', name='image_type'),
               type_=postgresql.ENUM('portrait', 'side_profile', 'full_body', 'other', name='image_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'other'::image_type"))
    # ### end Alembic commands ###
