"""init

Revision ID: f97bfa02af3d
Revises: 
Create Date: 2025-05-21 13:59:57.275335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97bfa02af3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('castings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_counter', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('image_counter <= 1', name='max_images_constraint'),
    sa.CheckConstraint('image_counter >= 0', name='min_images_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_castings_closed'), 'castings', ['closed'], unique=False)
    op.create_index(op.f('ix_castings_published'), 'castings', ['published'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('administrator', 'user', name='modelroles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('telegram_username')
    )
    op.create_table('casting_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['castings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('casting_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('casting_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['casting_id'], ['castings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('casting_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_casting_posts_closed_at'), 'casting_posts', ['closed_at'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('foot_size', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shoulder_width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('image_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('image_counter <= 3', name='max_images_constraint'),
    sa.CheckConstraint('image_counter >= 0', name='min_images_constraint'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_profiles_date_of_birth'), 'profiles', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_profiles_experience'), 'profiles', ['experience'], unique=False)
    op.create_index(op.f('ix_profiles_first_name'), 'profiles', ['first_name'], unique=False)
    op.create_index(op.f('ix_profiles_foot_size'), 'profiles', ['foot_size'], unique=False)
    op.create_index(op.f('ix_profiles_gender'), 'profiles', ['gender'], unique=False)
    op.create_index(op.f('ix_profiles_height'), 'profiles', ['height'], unique=False)
    op.create_index(op.f('ix_profiles_hip_width'), 'profiles', ['hip_width'], unique=False)
    op.create_index(op.f('ix_profiles_image_counter'), 'profiles', ['image_counter'], unique=False)
    op.create_index(op.f('ix_profiles_last_name'), 'profiles', ['last_name'], unique=False)
    op.create_index(op.f('ix_profiles_shoulder_width'), 'profiles', ['shoulder_width'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_index('ix_surname_name_lastname', 'profiles', ['first_name', 'last_name'], unique=False)
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('profile_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('casting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['casting_id'], ['castings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('profile_id', 'casting_id', name='uq_profile_id_casting_id')
    )
    op.create_index(op.f('ix_profile_responses_casting_id'), 'profile_responses', ['casting_id'], unique=False)
    op.create_index(op.f('ix_profile_responses_profile_id'), 'profile_responses', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_responses_profile_id'), table_name='profile_responses')
    op.drop_index(op.f('ix_profile_responses_casting_id'), table_name='profile_responses')
    op.drop_table('profile_responses')
    op.drop_table('profile_images')
    op.drop_index('ix_surname_name_lastname', table_name='profiles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_shoulder_width'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_image_counter'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_hip_width'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_height'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_gender'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_foot_size'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_first_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_experience'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_date_of_birth'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_casting_posts_closed_at'), table_name='casting_posts')
    op.drop_table('casting_posts')
    op.drop_table('casting_images')
    op.drop_table('users')
    op.drop_index(op.f('ix_castings_published'), table_name='castings')
    op.drop_index(op.f('ix_castings_closed'), table_name='castings')
    op.drop_table('castings')
    # ### end Alembic commands ###
